### ISSUE TITLE
Mapping Custom Templates to JavaScript Modules

### ISSUE THREAD

**Issue by sacr3dc0w** [bigcommerce/cornerstone#1339] opened 2018-09-03 21:56 UTC
https://stencil.bigcommerce.com/docs/js-101#map-custom

Not really an issue, I wanted to provide an alternative solution to the one in the documentation. After `pageClasses` is declared in `app.js`, add something along the lines of the code below.

```
const customClasses = {
    'pages/custom/category/custom-category': () => import('./theme/custom/custom-category'),
    'pages/custom/page/custom-page': () => import('./theme/custom/custom-page'),
    'pages/custom/product/custom-product': () => import('./theme/custom/custom-product'),
};
```

After `const context` is declared in `window.stencilBootstrap`, paste the follow:

```
const template = context.template;
const templateCheck = Object.keys(customClasses).indexOf(template);
```

Finally, we need to actually load the module if `templateCheck` is greater than `-1`. Paste the following code after `if (typeof pageClassImporter === 'function')`

```
if (templateCheck > -1) {
    // Find the appropriate page loader based on template
    const customClassImporter = customClasses[template];
    if (typeof customClassImporter === 'function') {
        const CustomClass = (await customClassImporter()).default;
        CustomClass.load(context);
    }
}
```
----------------------------

What `app.js` should look like when done.

```
__webpack_public_path__ = window.__webpack_public_path__; // eslint-disable-line

import 'babel-polyfill';
import $ from 'jquery';
import 'jquery-migrate';
import Global from './theme/global';

const getAccount = () => import('./theme/account');
const getLogin = () => import('./theme/auth');
const pageClasses = {
    account_orderstatus: getAccount,
    account_order: getAccount,
    account_addressbook: getAccount,
    shippingaddressform: getAccount,
    account_new_return: getAccount,
    'add-wishlist': () => import('./theme/wishlist'),
    account_recentitems: getAccount,
    account_downloaditem: getAccount,
    editaccount: getAccount,
    account_inbox: getAccount,
    account_saved_return: getAccount,
    account_returns: getAccount,
    login: getLogin,
    createaccount_thanks: getLogin,
    createaccount: getLogin,
    getnewpassword: getLogin,
    forgotpassword: getLogin,
    blog: () => import('./theme/blog'),
    blog_post: () => import('./theme/blog-post'),
    brand: () => import('./theme/brand'),
    brands: () => import('./theme/brands'),
    cart: () => import('./theme/cart'),
    category: () => import('./theme/category'),
    compare: () => import('./theme/compare'),
    page_contact_form: () => import('./theme/contact-us'),
    error: () => import('./theme/errors'),
    404: () => import('./theme/404-error'),
    giftcertificates: () => import('./theme/gift-certificate'),
    giftcertificates_balance: () => import('./theme/gift-certificate'),
    giftcertificates_redeem: () => import('./theme/gift-certificate'),
    default: () => import('./theme/home'),
    page: () => import('./theme/page'),
    product: () => import('./theme/product'),
    amp_product_options: () => import('./theme/product'),
    search: () => import('./theme/search'),
    rss: () => import('./theme/rss'),
    sitemap: () => import('./theme/sitemap'),
    newsletter_subscribe: () => import('./theme/subscribe'),
    wishlist: () => import('./theme/wishlist'),
    wishlists: () => import('./theme/wishlist'),
};

const customClasses = {
    'pages/custom/category/custom-category': () => import('./theme/custom/custom-category'),
    'pages/custom/page/custom-page': () => import('./theme/custom/custom-page'),
    'pages/custom/product/custom-product': () => import('./theme/custom/custom-product'),
};

/**
 * This function gets added to the global window and then called
 * on page load with the current template loaded and JS Context passed in
 * @param pageType String
 * @param contextJSON
 * @returns {*}
 */
window.stencilBootstrap = function stencilBootstrap(pageType, contextJSON = null, loadGlobal = true) {
    const context = JSON.parse(contextJSON || '{}');
    const template = context.template;
    const templateCheck = Object.keys(customClasses).indexOf(template);

    return {
        load() {
            $(async () => {
                // Load globals
                if (loadGlobal) {
                    Global.load(context);
                }

                // Find the appropriate page loader based on pageType
                const pageClassImporter = pageClasses[pageType];
                if (typeof pageClassImporter === 'function') {
                    const PageClass = (await pageClassImporter()).default;
                    PageClass.load(context);
                }

                if (templateCheck > -1) {
                    // Find the appropriate page loader based on template
                    const customClassImporter = customClasses[template];
                    if (typeof customClassImporter === 'function') {
                        const CustomClass = (await customClassImporter()).default;
                        CustomClass.load(context);
                    }
                }
            });
        },
    };
};
```

**Comment by el-rotny** [comment] 2018-09-05 04:45
@sacr3dc0w this was a great contribution since the documentation seems outdated and the loading the context in the same way as intended with the newest updates.

**Comment by el-rotny** [comment] 2018-09-05 05:12
I'll piggy back on what @sacr3dc0w posted and say that once you have those pieces, you custom js template import file would look something like 

assets/js/theme/custom/custom-page.js
```javascript
import PageManager from '../page-manager';
import $ from 'jquery';
import _ from 'lodash';
import utils from '@bigcommerce/stencil-utils';

export default class CustomPage extends PageManager {
    constructor(context) {
        super(context);
        this.$body = $('body');
    }
    onReady() {
        console.log('on load');
    }
}
```

**Comment by junedkazi** [comment] 2018-09-13 19:52
@sacr3dc0w this sounds really good. Would you be up for opening a PR to add all the necessary logic in `app.js` and keep `const customClasses = {}` as empty class so all users need to do is add the mapping and we can update the docs once the PR is merged.

**Comment by junedkazi** [comment] 2018-09-13 20:14
@karen-white FYI

**Comment by junedkazi** [comment] 2018-09-21 00:36
Fixed in https://github.com/bigcommerce/cornerstone/pull/1346

**Closed by junedkazi** 2018-09-21 00:36 UTC
