### ISSUE TITLE
After stencil start,it show me "Unauthorized",but i have no changed it

### ISSUE THREAD

**Issue by HATECORO** [bigcommerce/cornerstone#1810] opened 2020-09-01 02:26 UTC
![image](https://user-images.githubusercontent.com/26687497/91787892-81057480-ec3d-11ea-8807-1128079ae6fe.png)
my frends in other company also show this，same as my token error,please check it

**Comment by junedkazi** [comment] 2020-09-01 04:57
closing as a duplicate of https://github.com/bigcommerce/stencil-cli

**Closed by junedkazi** 2020-09-01 04:57 UTC
