### ISSUE TITLE
Brands not showing in json for product panels

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/cornerstone#1534] opened 2019-07-02 15:26 UTC
### ATTENTION: EXISTING INTERNAL ENGINEERING TICKET FLAG AS SUPPORT
After talking to BC support we could verify the presence of an internal engineering ticket. Maybe  

**Expected Behavior**
When displaying featured products or other panels on a product page, the json of the product panel should contain also the brand. 

**Current Behavior**
json contains 

...
"brand":
   "name": null 
...

despite a brand being configured for this product. Full json can be found at the bottom. 

**Steps to reproduce:** 
Could be reproduced with stock cornerstone. 

`{
        "id": 514,
        "sku": "R-iphone7-RSS-128",
        "name": "iPhone 7 Rosso 128 GB",
        "url": "https://www.ricomprostaging.it/iphone-7-rosso-128-gb-usato-ricondizionato-rigenerato/",
        "brand": {
          "name": null
        },
        "availability": "",
        "summary": "iPhone 7 128 GB Rosso Usato Ricondizionato Rigenerato\r\nStai pensando di acquistare un iPhone 7 128 GB Rosso usato e ricondizionato? Prova la vasta gamma che ti pu&ograve; offrire riCompro!\r\nCerchi...",
        "image": {
          "data": "https://cdn11.bigcommerce.com/s-pqeliom1as/images/stencil/{:size}/products/514/507/iPhone_7_Rosso__54803.1521135448.jpg?c=2",
          "alt": "iPhone 7 Rosso 128 GB Ricondizionato"
        },`

**Comment by karen-white** [comment] 2019-07-02 18:11
Hi @fthobe , we've logged a bug ticket on our end (STRF-6761) to investigate brand not showing in the page context for the Customers Also Viewed panel, but I'd like to do some additional troubleshooting with you to help us narrow down the issue. Can you link us to a page where you see the brand for the product "iPhone 7 Rosso 128 GB" returning null in the product context? Thank you!

**Comment by fthobe** [comment] 2019-07-02 18:22
The template file is currently work in progress therefor subject to changes but the error appears. 
https://www.ricomprostaging.it/iphone-7-rosso-128-gb-usato-ricondizionato-rigenerato/

**Comment by karen-white** [comment] 2019-07-02 18:57
Thank you @fthobe ! I can confirm that what you're seeing is consistent with our existing ticket: In the products.similar_by_views array, the brand name property returns null. We appreciate the report, and we'll keep you updated on the progress of the ticket.

**Comment by fthobe** [comment] 2019-07-02 18:58
Customer Support mentioned it's a client side issue, is it fixable by us?

**Comment by karen-white** [comment] 2019-07-02 21:38
@fthobe It's very likely that this is a server-side issue rather than something in the theme. From what we've been able to uncover so far, it looks like the issue is related to the way the data is served to the storefront from the core BC application. We'll keep you posted 👍

**Comment by fthobe** [comment] 2019-07-03 04:37
Hi @karen-white, I know I am incredibly harsh on bigcommerce sometimes, but can you please provide an ETA in terms of months so that we can decide to develop a workaround or stay put till it’s fixed?

**Comment by karen-white** [comment] 2019-07-03 16:09
@fthobe I'm hesitant to estimate a timeframe because we haven't yet added this ticket to an active sprint or fully scoped how much effort it will involve. We'll have a better idea of the ETA once it's been assigned. I'm sorry I can't be more specific, but I wouldn't want to give you information that becomes inaccurate if the team's priorities have to shift or the scope is more complex than we originally thought.

**Comment by tommm** [comment] 2019-07-04 15:09
To narrow this down further; `brand` appears for products without variants, but disappears for products with variants, in `products.similar_by_views`.

**Comment by fthobe** [comment] 2019-07-05 18:59
Hi @karen-white , please don't perceive this as being ungrateful for your response. We rely heavily on brands to filter products out of product panels and for the future also out of search results. It would be great to receive time scope (not in sense of tomorrow but in sense of months / trimesters) to have an idea if we need to write a work around or if we can rely on this feature returning. 

Fabian

**Comment by karen-white** [comment] 2019-07-08 16:09
Hi @fthobe , we've added this ticket to the next sprint, which will begin in a couple of weeks. We can say that it'll definitely be looked at within the next couple of weeks, although we can't say with certainty that there will be a resolution in that timeframe. We'll know more once we begin work on the ticket. I hope that gives you a better idea of where this sits on our timeline.

**Comment by fthobe** [comment] 2019-07-08 16:36
@karen-white this means we could also end up without a solution for another 4-6 months, right?

**Comment by karen-white** [comment] 2019-07-08 16:51
@fthobe I want to be transparent with you--it's a possibility. We want to resolve the issue within the sprint, but there can be complications that push back the timeline. An engineer will be assigned to look at it within the next couple of weeks, and we'll be sure to circle back with you once we've had a chance to work on the ticket.

**Comment by fthobe** [comment] 2019-07-08 16:54
Hi @karen-white That's a really fair and square answer, thank you :)

**Comment by karen-white** [comment] 2019-07-18 13:40
@fthobe Quick update on this issue--we're in code review right now, but we expect to start rolling out the fix for this issue over the next week. I'll update this thread again once it's fully deployed.

**Comment by fthobe** [comment] 2019-07-18 13:45
@karen-white yeahhhh

**Comment by karen-white** [comment] 2019-07-23 15:32
@fthobe Hey Fabian - the fix has now rolled out to all stores, and it looks like brand is now showing on yours. I'm going to go ahead and close out this issue, but please feel free to reopen if you're still experiencing the problem!

**Closed by karen-white** 2019-07-23 15:32 UTC

**Comment by fthobe** [comment] 2019-07-23 15:46
Some big BC love to you!
