### ISSUE TITLE
Quick view options applying to product display page options

### ISSUE THREAD

**Issue by ocvninfo** [bigcommerce/cornerstone#981] opened 2017-03-25 15:54 UTC
#### Expected behavior

When using the quick view pop up, I expect to see the options selected inside the quick view modal.

#### Actual behavior

The options aren't showing as selected in the quick view modal. Instead, they select the options inside the product display page that the modal is displaying over. 

#### Steps to reproduce

1. Go to a product detail page on a product with options (size and color)
2. Click "quick view" on one of the related products
3. While in the quick view modal, choose a product option. That option will not show as selected in quick view. When you return to the product display page, the option selected in quick view will apply to product detail page. 

Please check and fix this asap.

**Comment by bc-AlyssNoland** [comment] 2017-03-26 19:35
@ocvninfo Have you verified this only in a customized version of cornerstone or have you also checked an uncustomized version?

**Comment by ocvninfo** [comment] 2017-03-27 02:35
@bc-AlyssNoland I verified this issue in the original version of cornerstone.

**Comment by ocvninfo** [comment] 2017-04-10 09:29
any updates on this issue? This issue is still happening.

**Comment by EdFromBJCS** [comment] 2017-04-10 13:46
I see what @ocvninfo is saying. Just to clarify, this is an issue on product pages only, not category pages or the home page. Go to a product page, scroll down to "Related Products" and click to open up quick view. Click an option (size, for example). The form option will not show as selected, but if you close the model you will see that the option you selected has now been applied to the product on page you have open.

**Comment by ocvninfo** [comment] 2017-04-10 15:39
@EdFromBJCS Exactly like that (y)

**Comment by EdFromBJCS** [comment] 2017-08-30 18:01
STENCIL-3697 does not fix the issue. 

1. Go to a product page with options, [http://cornerstone-bold-demo.mybigcommerce.com/outpost-jacket/](http://cornerstone-bold-demo.mybigcommerce.com/outpost-jacket/) for example. 
2. Open up a quick view modal on one of the related products.
3. Try to select a size, notice that you will not be able to, but the price will change to reflect the price on product page behind the quick view modal.
4. Close the quick view modal. You will see that the size you tried unsuccessfully to select in the modal has now been selected on product page.

**Comment by PeteyRev** [comment] 2018-02-17 23:34
Seeing the same issue as @EdFromBJCS

**Comment by Ubersmake** [comment] 2019-04-09 22:51
Closing this issue as I can't reproduce it in the comment above on the Cornerstone Bold demo site: https://github.com/bigcommerce/cornerstone/issues/981#issuecomment-326071271

We've done a lot of work with how product options, variants, and SKUs are handled by the platform. A combination of any or all of these changes could have also contributed: #1347, #1261, #1176 .

**Closed by Ubersmake** 2019-04-09 22:51 UTC
Labels: bug
