### ISSUE TITLE
Optional product list options display as out of stock when product is tracked by SKU

### ISSUE THREAD

**Issue by ajm348** [bigcommerce/cornerstone#1083] opened 2017-09-04 16:34 UTC
### Expected behavior
Product list options should show as in stock when they are in stock and the base product is tracked by SKU.

### Actual behavior
Product list options show as out of stock (crossed out) when they are in stock and the base product is tracked by SKU. 
![nothingselected](https://user-images.githubusercontent.com/5883009/30033923-e0bcbb14-9163-11e7-9a78-a3742309e3a8.png)

However, they do behave correctly upon selecting them as far as add-to-cart functionality goes.
Product list option is out of stock:
![outofstockselected](https://user-images.githubusercontent.com/5883009/30033934-ee648ddc-9163-11e7-8797-718cd4e6806b.png)
Product list option is in stock:
![instockselected](https://user-images.githubusercontent.com/5883009/30033950-017bafea-9164-11e7-9c56-67c2e82fcd54.png)

### Steps to reproduce behavior
Add a product. Add an option to this product. Create a SKU using this product/option pairing. Change product tracking to be based upon SKUs. Add an optional product list option to the product. Preferably do all of this using the V3 API, or else I believe that an in stock product list option will also show up as out of stock when selected (unless something has changed in the last few weeks in the query to utils.api.productAttributes.optionChange, as this had been returning a False boolean for either purchasable or instock when using option sets, I can't recall which one, possibly both).

**Comment by ajm348** [comment] 2017-09-04 16:45
Here is my attempt to fix this, but it is certainly not ideal: https://github.com/ajm348/cornerstone/commit/a88d3edd02ffc76b013590fc7d3992cbc9e95bbb

No options selected:
![fixednoneselected](https://user-images.githubusercontent.com/5883009/30034361-7384b044-9166-11e7-94f2-ec1ebca5c528.png)
Out of stock option selected:
![fixedoutofstockselected](https://user-images.githubusercontent.com/5883009/30034365-7b14b16a-9166-11e7-94ad-30f1c2652d3b.png)
In stock option selected:
![fixedinstockselected](https://user-images.githubusercontent.com/5883009/30034370-81464936-9166-11e7-8c4f-53fb9fcbed25.png)

**Comment by fthobe** [comment] 2018-10-11 15:09
@PreciselyAlyss Hi Alyss, thank you so much for your contributions to this theme, just one question: this issue has been solved somewhere between 2.2.1 and 2.5.1, it would be great if you make it easier to track bugfixes for external template developers by attributing them correctly to the issues.

**Comment by fthobe** [comment] 2018-10-15 21:52
@ubersmake we have had this issue tested with customer support three days ago and it seems to be mitigated. If you can clarify the problem with two or three lines of comment I can set our developers on it and let them make a pull request.

**Comment by Ubersmake** [comment] 2018-10-15 22:11
@fthobe After going through the PRs for our internal backend services, it looks like there was a change in May surrounding out of stock behavior. The change in question would have made it to all stores by May 14th 2018. It lines up roughly with the move from Cornerstone 1.18.0 to 2.0.0.

Prior to this change, options would be marked as out of stock if **any** combination of options would result in out of stock.

Presently, options are only marked as out of stock when there's enough information to definitely determine that the currently selected options will result in an out of stock product.

I was able to reproduce this issue today on Cornerstone 2.5.1 by using the "Mark options as out of stock" option in `/manage/settings/inventory`. I'm wondering if that option accounts for the difference between what we're seeing.

**Comment by fthobe** [comment] 2018-12-26 22:45
Greetings @Ubersmake, was this bug lucky enough to win the milestone 3.0 lottery?

**Comment by fthobe** [comment] 2019-01-04 15:59
@Ubersmake Paul, do you have any idea if this issue has been resolved?

**Comment by karen-white** [comment] 2019-01-16 14:38
Hi @fthobe ,
It sounds like there’s been some confusion around this issue, both with our internal teams and in the way we’ve communicated this to merchants. Although there may have been a bug related to this behavior in the past, we’ve confirmed with our Catalog Engineering team that the issue should be resolved as long as inventory tracking for Product Pick Lists has been configured in the recommended way:

The first valid configuration for product pick list inventory tracking is to track by option and create SKUs for pick list options with inventory levels specified in the "SKU" tab. In order for this to work as intended, the merchant must create skus for these pick list selections and then individually set inventory from them. This configuration is intentionally not reading inventory from the product associated to the pick list option. 

The second way to configure inventory for your product with a product pick list option, is to track by product if the product using the pick list option has its own inventory, and then in the configuration of the pick list option itself, decide whether or not to subtract inventory from the product listed in the pick list option. This will decrement inventory in two places: once on the product chosen from the picklist, and once from the product using the pick list option. 

I hope that helps to clarify the way product pick list inventory tracking is intended to work. If you’re observing different behavior on your store after setting up your products in one of these 2 ways, please be sure to get in touch with our Technical Support team to report the issue.

**Comment by bc-zoharmuzafi** [comment] 2019-04-11 20:00
Closing this issue due to inactivity

**Closed by bc-zoharmuzafi** 2019-04-11 20:00 UTC
Labels: bug, support

**Comment by fthobe** [comment] 2019-04-11 20:31
@bc-zoharmuzafi @Ubersmake you mean it's fixed or it is not getting fixed?
