### ISSUE TITLE
BCData missing 'price'

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/cornerstone#1673] opened 2020-05-13 00:53 UTC
Hi all, did something change on BigCommerce sometime in the last few hours. Suddenly the `window.BCData.product_attributes` does not contain a `price` key. All of my product pages are broken.

Any idea what's going on? I'm on hold now trying to talk to phone support, but no one is answering.

Please help!

**Comment by flyingL123** [comment] 2020-05-13 01:30
This json variable used to have a 'price' key with all the pricing information for the initial variant. Where did it go???

![image](https://user-images.githubusercontent.com/2486712/81761365-c38d2080-9497-11ea-92eb-e95439241e4d.png)

**Comment by junedkazi** [comment] 2020-05-13 02:06
@flyingL123 can you share your store details. You can email me at my first name dot last name at bigcommerce dot com

**Comment by flyingL123** [comment] 2020-05-13 02:09
Thanks for the follow up @junedkazi I just emailed you.

**Comment by junedkazi** [comment] 2020-05-13 04:19
@flyingL123 i am going to go ahead and close this issue.

**Closed by junedkazi** 2020-05-13 04:19 UTC

**Comment by flyingL123** [comment] 2020-05-18 18:27
Guys, come on! Same issue happening again. @junedkazi are you there?

<img width="1433" alt="Screen Shot 2020-05-18 at 2 25 39 PM" src="https://user-images.githubusercontent.com/2486712/82247031-bcd93000-9913-11ea-94d8-02aa6c460048.png">

**Comment by flyingL123** [comment] 2020-05-18 18:28
I deployed a temporary fix on our domain, but what happened to the `price` attribute again? Is the same experiment from before running? I thought a test was written so this wouldn't happen again.

**Comment by junedkazi** [comment] 2020-05-18 18:30
@flyingL123 let me take a quick look.

**Comment by flyingL123** [comment] 2020-05-18 18:40
@junedkazi it's back, thanks. But, what happened? Is this presence of this price attribute not something I should rely on going forward? It's worked well for about 7 years, but as you know this is now the second time it's disappeared without warning rendering our site completely unusable by customers.

**Comment by bookernath** [comment] 2020-05-18 19:04
@flyingL123 apologies for the disruption experienced on your end. This was caused by an A/B rollout of some code which we've since rolled back. We'll make sure it gets properly fixed before we roll it out again.

As a note, keep in mind that our OSS GitHub repos are monitored only intermittently, so for something time-sensitive like this it's typically best to get in touch with our support organization directly: https://support.bigcommerce.com/s/

**Comment by flyingL123** [comment] 2020-05-18 19:33
@bookernath  - that was the explanation for why this happened 6 days ago. After which I was assured it was not going to happen again. Now it just happened again. I understand things go wrong and you are all working on complex systems, so I'm not trying to give anybody a hard time. I am just making sure you're aware that this is the second time it happened so you can properly investigate. The first time was a mistake with an experiment rollout, I get that. The second time it was never supposed to happen again.

Also, again, just want to make sure you have all of the information: The support organization is completely useless in emergencies like this. The first thing I did when this first came up 6 days ago was call into support. I showed them exactly what the problem was, but they only know how to go through their standard troubleshooting steps. They do not have the technical expertise to have any idea what I'm talking about when I refer to "the price attribute of the BCData json string usually written to the page by your server".

The representative was not able to find any evidence of any issues related to pricing, said it had to be escalated to Tier 2 support, and that I would "probably" hear back from them sometime in the next 24 hours. If I relied only on that method my store would have been unusable for at least 2 days while the case worked its way through the system. It would have eventually made its way to you to finally be fixed.

Meanwhile, I posted the issue on Github and @junedkazi got back to me and the issue was completely solved within 20 minutes.

My point with all of this is that as an "advanced" user of BigCommerce for years, building our own theme with advanced customizations (for which we won the grand prize in your first ever innovation awards in 2016), I am consistently frustrated by the lack of support and transparency from BigCommerce. If I am calling into your support channels, it's because I have determined there is a problem. Not a "how do I update my logo" type of problem; a real problem. I know the system better than 90% of the support representatives. There needs to be some way for developers like me to get the proper help, quickly, when there is a real issue. A more direct line to the engineers who actually know what's going on.

Sorry to unload on you. Just food for thought.

**Comment by bookernath** [comment] 2020-05-18 20:02
@flyingL123 definitely appreciate the direct and honest feedback - it helps us improve.

One of the areas where we're investing at the moment is around a better plan to support developers such as yourself, because we know there's a gap at the moment where folks like yourself don't always get what you need when you call us on the phone. Your feedback is well timed in that regard, because we're in the middle of planning how to improve our processes for exactly this sort of issue. I'll be passing it upwards.

In terms of the issue recurring - that was frankly due to a miscommunication internally on our end, a combination of human error and our systems which tell us which code releases have made it to which stages of production misguiding us. I'm sure it feels like we fumbled pretty hard on this one on your end, but I can assure you the folks involved are taking this seriously putting measures in place to prevent things like this happening in the future. I've been asked to pass our apologies from the engineering team directly.

I can assure you that this feature is very much intended to be supported going forward (just to answer your direct question), and we certainly appreciate your continued business and contributions.

**Comment by flyingL123** [comment] 2020-05-18 20:12
@bookernath great thank you for the information, much appreciated. If I can be of any help as you figure out how to support developers, don't hesitate to reach out. I'm happy to speak about my experience and how it can be improved.
