### ISSUE TITLE
Blurry text and images in quick view modals

### ISSUE THREAD

**Issue by ocvninfo** [bigcommerce/cornerstone#993] opened 2017-04-10 09:27 UTC
As i mentioned on issue heading.
The quick view popup is blurry.
![image](https://cloud.githubusercontent.com/assets/3072481/24854951/4910a0c2-1e0a-11e7-8c49-548d987ccc83.png)

other popup same problem:
![image](https://cloud.githubusercontent.com/assets/3072481/24855023/7349e2b8-1e0a-11e7-9aa5-62959dfa27c0.png)

Is there a way to fix this issue?

**Comment by bc-AlyssNoland** [comment] 2017-04-11 21:04
Based on [this](https://github.com/bigcommerce/cornerstone/blob/master/templates/components/products/product-view.html#L159), it should be using the default product image in the quick view modal. Have you tried uploading a higher resolution photo to see if that clears up the problem, @ocvninfo?

**Comment by ocvninfo** [comment] 2017-04-14 06:56
@bc-AlyssNoland Thank for your reply. But what i mean is blurry all text in the popup.
The popup work fine on Firefox but blurry on Chrome.

**Comment by EdFromBJCS** [comment] 2017-04-14 13:15
@bc-AlyssNoland @ocvninfo I have noticed this as well. The title of this issue is misleading because it is not just pictures, text and other elements are blurry as well. It's subtle, but unmistakable. Looks kind of like the lossy analog picture you get from a VGA-connected monitor. Strange.

**Comment by ThemeValeBC** [comment] 2017-05-03 01:35
@EdFromBJCS I checked on firefox, The quick view popup working correctly. But it is blurry on chrome

**Comment by sacr3dc0w** [comment] 2017-05-11 02:16
It would seem that translate(-50%, -50%) is calculating a pixel value on both axes with a decimal place, causing subpixel rendering. One solution could be subtracting 0.5px from the Y-axis. That solved the problem in Chrome and Safari based off my testing.

**Comment by ocvninfo** [comment] 2017-05-12 08:30
@sacr3dc0w  Thank you for this.
But it still blurry when popup resizing.

**Comment by Ubersmake** [comment] 2019-04-09 23:00
Closing this issue as I can no longer reproduce it. There are image-related PRs in #1094, #1096, #1104, and #1358. As some of the comments above mentioned, this could have also been a browser-related bug that's been fixed since this issue was first reported.

**Closed by Ubersmake** 2019-04-09 23:00 UTC
Labels: bug
