### ISSUE TITLE
Search pagination displays no content when switching between sections and one section has more pages then the other

### ISSUE THREAD

**Issue by jkelly-cas** [bigcommerce/cornerstone#1170] opened 2018-02-23 23:57 UTC
Note, the [Cornerstone demo](http://cornerstone-light-demo.mybigcommerce.com/search.php?search_query=blog&section=content&page=2), does not have enough content to view this issue, but is reproducible.

### Expected behavior
When switching between sections on a search, if one section has 100 items, and the other has 10, if you're viewing content on page=4, and switch to the other section, it should show either it's last page, or reset the pagination.

### Actual behavior
When using the pagination, and switching between sections, the page counter is not adjusted or reset, and wrongly displays no content.

### Steps to reproduce behavior
Search a term that has pages worth of products, and a few blog posts, and use the pagination til it's above the page amount of the blog section ( or vice versa ), and switch sections. The page counter doesn't adjust itself to reflect the page amount discrepancy, and shows no items.
![image](https://user-images.githubusercontent.com/14987740/36622278-32b9543e-18b1-11e8-83b2-4605029bcce6.png)

This is more readily viewable when both sections have a discrepancy in page numbers.

**Comment by funvill** [comment] 2018-04-04 19:00
Re-posted https://forum.bigcommerce.com/s/question/0D51B00004IKmhsSAD/

**Comment by davidwrpayne** [comment] 2019-04-18 23:06
Duplicate of https://github.com/bigcommerce/cornerstone/issues/1312

**Closed by davidwrpayne** 2019-04-18 23:06 UTC
Labels: duplicate
