### ISSUE TITLE
List View - Improve / Tidy Alignment

### ISSUE THREAD

**Issue by GeorgeLondon** [bigcommerce/cornerstone#969] opened 2017-03-17 15:57 UTC
Great to have a List View now, thanks (fixed in STENCIL-3194) - I've just activated it in our test store.

The layout of the columns on the List View is irregular, based on the size of the thumbnail and the amount of text in the description.

I suspect this could probably be resolved by imposing a width on the thumbnail image and on the Title & Description elements.

Screenshot below with red guidelines to show where sections are not aligned in the way I expect them to be.

![image](https://cloud.githubusercontent.com/assets/26487893/24051012/9c6263ea-0b28-11e7-8696-8844231bc3db.png)

This is even more pronounced on the Search Results page. Screenshot below with red guidelines.

![image](https://cloud.githubusercontent.com/assets/26487893/24051187/401e8c02-0b29-11e7-81b9-9328089c6fbc.png)

Third screenshot from the Brands page.

![image](https://cloud.githubusercontent.com/assets/26487893/24051506/2792b0fe-0b2a-11e7-8973-04ac8b487c23.png)

All screenshots from Win10/Chrome.

**Comment by m0000g** [comment] 2017-03-21 20:13
This could be fixed ... perhaps with flexbox?
I would love to help

**Comment by bc-AlyssNoland** [comment] 2017-03-23 19:40
@m0000g Feel free! We welcome PRs :)

**Comment by GeorgeLondon** [comment] 2017-03-24 11:33
A little more info;

What appears to be happening is that some elements expand depending on the width of the browser, but they are not expanding uniformly down the page. The reason this was more pronounced on the Search Results page is because the content area on that page is effectively wider (because there is no LH block).

The issue is becoming less obvious as we have been going through the process of populating our products with (equal sized) images this week, but we are still seeing it.

**Comment by Ubersmake** [comment] 2018-12-18 00:37
I'm closing this issue mostly because of age. I'm hopeful that somewhere in the last year's worth of changes this issue was addressed. I certainly can't reproduce it anymore. One of these is likely to have contributed:

https://github.com/bigcommerce/cornerstone/pull/1137 - Released in 1.11.0
https://github.com/bigcommerce/cornerstone/pull/1033 - Released in 1.8.2
https://github.com/bigcommerce/cornerstone/pull/980 - Released in 1.6.3

Cornerstone 1.6.3 was released on March 28, 2017.

For the record, this is what List View looks like now. The first image's source is very, very large and of different dimensions than everything else:

![screen shot 2018-12-17 at 4 26 48 pm](https://user-images.githubusercontent.com/1546172/50124515-d9060880-0219-11e9-9910-b5a5eec4bd08.png)

@GeorgeLondon , @m0000g , please feel free to re-open this Issue if it isn't actually fixed on Cornerstone, which as of this writing is at 2.6.0.

**Closed by Ubersmake** 2018-12-18 00:37 UTC
Labels: beginner
